// sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // Top doc
    'intro',

    // Getting Started
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/account-setup',
        'getting-started/faq',
        'getting-started/system-requirements',
      ],
    },

    // Lifecycle (open the section page directly, no dropdown levels)
    {
      type: 'category',
      label: 'Lifecycle',
      items: [
        { type: 'doc', id: 'lifecycle/discovery/index', label: 'Discovery' },
        { type: 'doc', id: 'lifecycle/design/index', label: 'Design' },
        { type: 'doc', id: 'lifecycle/deployment/index', label: 'Deployment' },
        { type: 'doc', id: 'lifecycle/maintenance/index', label: 'Maintenance' },
      ],
    },

    // Recommendations
    {
      type: 'category',
      label: 'Recommendations',
      link: { type: 'doc', id: 'recommendations/index' },
      items: ['recommendations/speakers-for-acoustics'],
    },

    // Tutorials (no link to tutorials/index; just the existing docs)
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/acoustics-guide',
        'tutorials/scan-marker-guide',
      ],
    },
    // Video Tutorials
    {
      type: 'category',
      label: 'Video Tutorials',
      link: {
        type: 'generated-index',
        title: 'Video Tutorials',
        description: 'Step-by-step video guides for common workflows.',
      },
      items: ['video-tutorials/video-acoustics-guide'],
    },
    // Release Notes (autogenerate from folder)
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'release-notes' }],
    },
  ],
};

export default sidebars;
