// sidebars.ts
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Use the default id Docusaurus looks for: "tutorialSidebar"
  tutorialSidebar: [
    // Top item: Welcome
    { type: 'doc', id: 'intro', label: 'Welcome to Better Meeting Rooms' },

    // Getting Started
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/account-setup',
        'getting-started/faq',
        'system-requirements',
      ],
    },

    // Lifecycle (direct docs, no sub-sub pages)
    {
      type: 'category',
      label: 'Lifecycle',
      items: [
        { type: 'doc', id: 'lifecycle/discovery/index',    label: 'Discovery' },
        { type: 'doc', id: 'lifecycle/design/index',       label: 'Design' },
        { type: 'doc', id: 'lifecycle/deployment/index',   label: 'Deployment' },
        { type: 'doc', id: 'lifecycle/maintenance/index',  label: 'Maintenance' },
      ],
    },

    // Recommendations
    {
      type: 'category',
      label: 'Recommendations',
      items: [
        { type: 'doc', id: 'recommendations/index',                 label: 'Overview' },
        { type: 'doc', id: 'recommendations/speakers-for-acoustics', label: 'Speakers for Acoustics' },
      ],
    },

    // Tutorials (auto)
   {
     type: 'category',
     label: 'Tutorials',
     link: { type: 'doc', id: 'tutorials/index' },          // 👈 gives the category a landing page
     items: [{ type: 'autogenerated', dirName: 'tutorials' }], // 👈 will list any tutorial docs you add later
   },

    // Release Notes (auto)
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'release-notes' }],
    },
  ],
};

export default sidebars;
